### ISSUE TITLE
Does this work for T490s?

### ISSUE THREAD

**Issue by kenjican** [mahronid/thinkpad-x390-hackintosh#1]
My T490s doesn't work with T490 EFI. It hangs in the installation.As I know X390's spec is almost the same as T490s.I'll try this tomorrow

**Comment by mahronid** [comment]
> My T490s doesn't work with T490 EFI. It hangs in the installation.As I know X390's spec is almost the same as T490s.I'll try this tomorrow

I think if the specs are the same as the Thinkpad X390, it should work. Try the install EFI first and don't forget to change your SMBIOS (use MacBookPro15,4).
